apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sol03-web-efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sol03-web-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03620a3b6d6550b64      
---
apiVersion: v1
kind: Service
metadata:
  name: sol03-web-server
  labels:
    app: web-server
spec:
  type: ClusterIP
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: sol03-web-server
          image: 381491941914.dkr.ecr.ap-northeast-2.amazonaws.com/mycicd:sol03-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: sol03-web-efs
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sol03-web-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40
