apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was-server
  template:
    metadata:
      labels:
        app: was-server
    spec:
      containers:
      - name: reca3team-was-server
        image: beenlee0930/mycicd-tomcat
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reca3team-was-server-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was-server
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40
      
